# General setup to build and run tests on the project whenever committing
sudo: required
services:
  - docker
before_install:
  - docker build -t jahhasangjekaj/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true jahhasangjekaj/react-test npm test -- --coverage

after_success:
    - docker build -t jahhasangjekaj/multi-client ./client
    - docker build -t jahhasangjekaj/multi-nginx ./nginx
    - docker build -t jahhasangjekaj/multi-server ./server
    - docker build -t jahhasangjekaj/multi-worker ./worker
    # Log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to the docker hub
    - docker push jahhasangjekaj/multi-client
    - docker push jahhasangjekaj/multi-nginx
    - docker push jahhasangjekaj/multi-server
    - docker push jahhasangjekaj/multi-worker

# Deploy to production only when thera are changes to master branch
# deploy:
#   edge: true
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-269924676398"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
