sudo: required
services:
  - docker

before_install:
  - docker build -t jhasangjekaj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jhasangjekaj/react-test npm test -- --coverage

after_success:
  - docker build -t jhasangjekaj/multi-client ./client
  - docker build -t jhasangjekaj/multi-nginx ./nginx
  - docker build -t jhasangjekaj/multi-server ./server
  - docker build -t jhasangjekaj/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jhasangjekaj/multi-client
  - docker push jhasangjekaj/multi-nginx
  - docker push jhasangjekaj/multi-server
  - docker push jhasangjekaj/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-269924676398"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
